[window]
dynamic_padding = true
# resize_increments = true
opacity = 0.9

[mouse]
bindings = [
  { mouse = "Right", action = "Copy" }
]

[scrolling]
multiplier = 10

[font]
size = 11
normal = { family = "IosevkaTermSlab NF" }

