[tools]
age = "latest"
atuin = "latest"
awscli = "latest"
bat = "latest"
bun = "latest"
chezmoi = "latest"
dbmate = "latest"
deno = "latest"
difftastic = "latest"
eza = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
golang = "latest"
helm = "latest"
k3s = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
kubectx = "latest"
minikube = "latest"
neovim = "latest"
node = "18"
rg = "latest"
sops = "latest"
starship = "latest"
stern = "latest"
taplo = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = []
trusted_config_paths = ["~/code"]
